name: Deploy
on:
  push:
    branches: [master]

defaults:
  run:
    working-directory: app

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: ls -lah

      - name: Deploy via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "${{ GITHUB_WORKSPACE }}/out/*"
        target: "/var/www/tn1gg"
        # strip_components: 5
